# Playbook to setup workstation and create osp network, router, SG and ssh keypair

- hosts: localhost
  become: yes
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       groups: workstation


- hosts: workstation
  become: yes
  roles:
    - setup-workstation

- import_playbook: site-install-isolated-node.yml 

